# Generated by Django 2.1.5 on 2021-05-19 07:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('yangiliklar', '0002_auto_20210505_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangilik',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='qisqa',
            field=tinymce.models.HTMLField(),
        ),
    ]
